### ISSUE TITLE
Loving this fantastic plugin. Just trying to contact the creator and thank him personally.

### ISSUE THREAD

**Issue by LogicPy** [frinky04/ElevenLabsTTS-UnrealEngine#1]
I'm using your epic/beautiful vocal output plugin for my newest Lollms plugin I plan to sell on the marketplace very soon.

[Video Demonstration for my plugin using your beautiful vocal ai output plugin too](https://www.youtube.com/watch?v=5xq_aCrvE2s)

Thanks a million for posting this on GitHub instead of on the marketplace.

I'm willing to negotiate an amount of income for your beautiful contribution too. Thanks friend. Your fantastic ElevenLabs Ai vocal output piece is a super important piece for my plugin. Thanks friend!

**Comment by frinky04** [comment]
np, code is free to distribute
